# config.yml
sunbeam:
    donation:
      request: https://babybeam.henselforcongress.com/anedot
      run_count: 2000
      time_machine: 45
      repeaters: 750
      amount:
        min: 2
        max: 1000
      zip_code:
        weight: 60
        primary:
          - 22003
          - 22041
          - 22042
          - 22043
          - 22044
          - 22046
          - 22060
          - 22079
          - 22101
          - 22102
          - 22150
          - 22151
          - 22153
          - 22201
          - 22202
          - 22203
          - 22204
          - 22205
          - 22206
          - 22207
          - 22209
          - 22211
          - 22213
          - 22214
          - 22301
          - 22302
          - 22303
          - 22304
          - 22305
          - 22306
          - 22307
          - 22308
          - 22309
          - 22310
          - 22311
          - 22312
          - 22314
          - 22315



